/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author LENOVO-PC
 */
public class edusysJFrame extends javax.swing.JFrame {

    /**
     * Creates new form edusys
     */
    public edusysJFrame() {
        initComponents();
        intit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangxuat = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btnchuyende = new javax.swing.JButton();
        btnnguoihoc = new javax.swing.JButton();
        btnkhoahoc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnhuongdan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblacc = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniDoiMK = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mninguoihoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnichuyende = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnikhoahoc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniqlchuyenvien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniNguoiHoc = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniBangDiem = new javax.swing.JMenuItem();
        mniDiemChuyenDe = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniDoanhThu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mbiHuongDan = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnigioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ quản lý đào tạo");

        jToolBar1.setRollover(true);

        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Log out.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.setFocusable(false);
        btnDangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangxuat.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnDangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDangxuat);

        btnketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Stop.png"))); // NOI18N
        btnketthuc.setText("Kết thúc");
        btnketthuc.setFocusable(false);
        btnketthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnketthuc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnketthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnketthuc);
        jToolBar1.add(jSeparator10);

        btnchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Lists.png"))); // NOI18N
        btnchuyende.setText("Chuyên đề");
        btnchuyende.setFocusable(false);
        btnchuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnchuyende.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnchuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnchuyende);

        btnnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Conference.png"))); // NOI18N
        btnnguoihoc.setText("Người học");
        btnnguoihoc.setFocusable(false);
        btnnguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnguoihoc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnnguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnguoihoc);

        btnkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Certificate.png"))); // NOI18N
        btnkhoahoc.setText("Khóa học");
        btnkhoahoc.setFocusable(false);
        btnkhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhoahoc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnkhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkhoahoc);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Boy.png"))); // NOI18N
        jButton1.setText("Học viên");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator11);

        btnhuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Globe.png"))); // NOI18N
        btnhuongdan.setText("Hướng dẫn");
        btnhuongdan.setFocusable(false);
        btnhuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhuongdan.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnhuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuongdanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhuongdan);

        lblacc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Gear.png"))); // NOI18N
        lblacc.setText("Hệ quản lý đào tạo");

        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Alarm.png"))); // NOI18N
        lbldongho.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblacc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldongho))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblacc)
                    .addComponent(lbldongho)))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/logo-small.png"))); // NOI18N
        jLabel1.setOpaque(true);

        jMenu1.setText("Hệ thống");

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Key.png"))); // NOI18N
        mniDangNhap.setText("Đăng nhập");
        jMenu1.add(mniDangNhap);
        jMenu1.add(jSeparator1);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Log out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangXuat);
        jMenu1.add(jSeparator2);

        mniDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Refresh.png"))); // NOI18N
        mniDoiMK.setText("Đổi mật khẩu");
        mniDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMKActionPerformed(evt);
            }
        });
        jMenu1.add(mniDoiMK);
        jMenu1.add(jSeparator3);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Stop.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(mniKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mninguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Conference.png"))); // NOI18N
        mninguoihoc.setText("Người học");
        mninguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninguoihocActionPerformed(evt);
            }
        });
        jMenu2.add(mninguoihoc);
        jMenu2.add(jSeparator4);

        mnichuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Lists.png"))); // NOI18N
        mnichuyende.setText("Chuyên đề");
        mnichuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnichuyendeActionPerformed(evt);
            }
        });
        jMenu2.add(mnichuyende);
        jMenu2.add(jSeparator5);

        mnikhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Certificate.png"))); // NOI18N
        mnikhoahoc.setText("Khóa học");
        mnikhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnikhoahocActionPerformed(evt);
            }
        });
        jMenu2.add(mnikhoahoc);
        jMenu2.add(jSeparator6);

        mniqlchuyenvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Clien list.png"))); // NOI18N
        mniqlchuyenvien.setText("Quản lý nhân viên");
        mniqlchuyenvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniqlchuyenvienActionPerformed(evt);
            }
        });
        jMenu2.add(mniqlchuyenvien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mniNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/User group.png"))); // NOI18N
        mniNguoiHoc.setText("Người học từng năm");
        mniNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoiHocActionPerformed(evt);
            }
        });
        jMenu3.add(mniNguoiHoc);
        jMenu3.add(jSeparator7);

        mniBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Card file.png"))); // NOI18N
        mniBangDiem.setText("Bảng điểm khóa...");
        mniBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangDiemActionPerformed(evt);
            }
        });
        jMenu3.add(mniBangDiem);

        mniDiemChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Bar chart.png"))); // NOI18N
        mniDiemChuyenDe.setText("Bảng điểm từng khóa");
        mniDiemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemChuyenDeActionPerformed(evt);
            }
        });
        jMenu3.add(mniDiemChuyenDe);
        jMenu3.add(jSeparator8);

        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Money.png"))); // NOI18N
        mniDoanhThu.setText("Doanh thu từng chuyên đề...");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        jMenu3.add(mniDoanhThu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mbiHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mbiHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Globe.png"))); // NOI18N
        mbiHuongDan.setText("Hướng dẫn sử dụng");
        jMenu4.add(mbiHuongDan);
        jMenu4.add(jSeparator9);

        mnigioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Hinh/Brick house.png"))); // NOI18N
        mnigioithieu.setText("Giới thiệu phần mềm");
        mnigioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnigioithieuActionPerformed(evt);
            }
        });
        jMenu4.add(mnigioithieu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void mnichuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnichuyendeActionPerformed
        // TODO add your handling code here:
        new quanlyCDJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnichuyendeActionPerformed

    private void mninguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninguoihocActionPerformed
        // TODO add your handling code here:
        new quanlyNHocJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mninguoihocActionPerformed

    private void mnikhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnikhoahocActionPerformed
        // TODO add your handling code here:
        new quanlyKHJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnikhoahocActionPerformed

    private void mniqlchuyenvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniqlchuyenvienActionPerformed
        // TODO add your handling code here:
        new quanlyNVQTJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniqlchuyenvienActionPerformed

    private void btnchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyendeActionPerformed
        // TODO add your handling code here:
        new quanlyCDJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnchuyendeActionPerformed

    private void btnnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnguoihocActionPerformed
        // TODO add your handling code here:
        new quanlyNHocJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnnguoihocActionPerformed

    private void btnkhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoahocActionPerformed
        // TODO add your handling code here:
        new quanlyKHJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnkhoahocActionPerformed

    private void mnigioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnigioithieuActionPerformed
        // TODO add your handling code here:
        new gioithieuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnigioithieuActionPerformed

    private void mniDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMKActionPerformed
        // TODO add your handling code here:
        new doiMKJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniDoiMKActionPerformed

    private void mniNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoiHocActionPerformed
        // TODO add your handling code here:
        this.openThongKe(0);
    }//GEN-LAST:event_mniNguoiHocActionPerformed

    private void mniBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangDiemActionPerformed
        // TODO add your handling code here:
        this.openThongKe(1);
    }//GEN-LAST:event_mniBangDiemActionPerformed

    private void mniDiemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemChuyenDeActionPerformed
        // TODO add your handling code here:
        this.openThongKe(2);
    }//GEN-LAST:event_mniDiemChuyenDeActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        // TODO add your handling code here:
        this.openThongKe(3);
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void btnhuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuongdanActionPerformed
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_btnhuongdanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new quanlyHocVien(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edusysJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnchuyende;
    private javax.swing.JButton btnhuongdan;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JButton btnkhoahoc;
    private javax.swing.JButton btnnguoihoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblacc;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JMenuItem mbiHuongDan;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDiemChuyenDe;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoiMK;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniNguoiHoc;
    private javax.swing.JMenuItem mnichuyende;
    private javax.swing.JMenuItem mnigioithieu;
    private javax.swing.JMenuItem mnikhoahoc;
    private javax.swing.JMenuItem mninguoihoc;
    private javax.swing.JMenuItem mniqlchuyenvien;
    // End of variables declaration//GEN-END:variables

    private void intit() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
        new chaoJDialog(this, true).setVisible(true);
        new dangnhapJDialog(this, true).setVisible(true);

        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss:a");
                String text = formater.format(now);
                lbldongho.setText(text);
            }
        }).start();
        
        String b=  Auth.a();
        lblacc.setText(b);
    }

    void ketthuc() {
        if (MsgBox.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
            System.exit(0);

        }
    }

    void dangXuat() {
        Auth.clear();
        new dangnhapJDialog(this, true).setVisible(true);
       
            
    }
    void openDoiMatKhau() {
        if(Auth.isLogin())
        new doiMKJDialog(this, true).setVisible(true);
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
            
    }
    void openNhanVien() {
        if(Auth.isLogin())
        new quanlyNVQTJDialog(this, true).setVisible(true);
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
            
    }
    void openKhoaHoc() {
        if(Auth.isLogin())
        new quanlyKHJDialog(this, true).setVisible(true);
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
            
    }
    void openChuyenDe() {
        if(Auth.isLogin())
        new quanlyCDJDialog(this, true).setVisible(true);
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
            
    }
    void openNguoiHoc() {
        if(Auth.isLogin())
        new quanlyNHocJDialog(this, true).setVisible(true);
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
            
    }
    void openGioiThieu() {
        if(Auth.isLogin())
        new gioithieuJDialog(this, true).setVisible(true);
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
            
    }
    void openThongKe(int index) {
        if(Auth.isLogin()){
            if(index==3&&!Auth.isManager()){
                MsgBox.alert(this, "Bạn không có quyền xem thông tin danh thu");
            }else{
                tonghopTKJFrame tkwin=new tonghopTKJFrame();
                tkwin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                tkwin.setVisible(true);
                tkwin.selectTab(index);
            }
        }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
            
    }
    void openHuongDan(){
        try{
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        }catch(IOException e){
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn");
        }
    }
   
    
}
